POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzc0NjQ4NDA2LCJ1c2VySWQiOjB9.2X5olp5jk7IftCp2HubHTcoM_ZqeTr1ifAkhhexlvQI

{
    "name":"Test event",
    "description" :"a test event",
    "location":"A test location",
    "dateTime":"2025-01-01T15:30:00.000Z"
}