PUT http://localhost:8080/events/1
Content-Type: application/json

{
    "name":"update event 1",
    "description" :"a test event 1",
    "location":"A test location1",
    "dateTime":"2025-01-01T15:30:00.000Z"
}